export const BrevoTemplateIds = {
  EMAIL_CONFIRMATION: 32,
  RESET_PASSWORD: 42,
  APPLICATION_SUBMITTED: 35,
  APPLICATION_INVITED: 37,
  APPLICATION_REJECTED: 39,
  REIMBURSEMENT_SUBMITTED: 36,
  REIMBURSEMENT_APPROVED: 40,
  REIMBURSEMENT_DECLINED: 41,
} as const;
